### ISSUE TITLE
how do I install portfolio_tools? 

### ISSUE THREAD

**Issue by siddharthgaur** [MOSEK/PortfolioOptimization#1]
I found a package portfolio-tools, but it doesn't seem to support DataReader, compute_inputs etc

**Comment by aszekMosek** [comment]
Do you mean https://github.com/MOSEK/PortfolioOptimization/blob/main/python/notebooks/portfolio_tools.py ? It is there in the folder with all the notebooks, and each colab notebook downloads it in its first cell.
