### ISSUE TITLE
Multiple mean variance-portfolio_tools 

### ISSUE THREAD

**Issue by firdevsuykun** [MOSEK/PortfolioOptimization#2]
from portfolio_tools import data_download, DataReader, compute_inputs, portfolio_tools does not exist in the web.How I install in anaconda?I saw you add portfolio_tools as a separate folder,but stocks data does not exist

**Comment by aszekMosek** [comment]
See the answer in #1 

It is a file distributed alongside with the notebooks in https://github.com/MOSEK/PortfolioOptimization/tree/main/python/notebooks

Stock data is something you have to obtain yourself, the instructions are at the beginning of each notebook where it is relevant. We do not own the stock data so it is not provided. You can for example generate your own or download it. I quote:

```
# Data downloading:
# If the user has an API key for alphavantage.co, then this code part will download the data. 
# The code can be modified to download from other sources. To be able to run the examples, 
# and reproduce results in the cookbook, the files have to have the following format and content:
# - File name pattern: "daily_adjusted_[TICKER].csv", where TICKER is the symbol of a stock. 
# - The file contains at least columns "timestamp", "adjusted_close", and "volume".
# - The data is daily price/volume, covering at least the period from 2016-03-18 until 2021-03-18, 
# - Files are for the stocks PM, LMT, MCD, MMM, AAPL, MSFT, TXN, CSCO.
list_stocks = ["PM", "LMT", "MCD", "MMM", "AAPL", "MSFT", "TXN", "CSCO"]
list_factors = []
alphaToken = None
 
list_tickers = list_stocks + list_factors
if alphaToken is not None:
    data_download(list_tickers, alphaToken)  
```
